plugins:
  master_sso_enabled:
    default: true
  master_sso_admin_admin_required:
    default: true
  master_sso_admin_tl_required:
    default: 3
  master_sso_moderator_tl_required:
    default: 2
